name: CI for Angular

on:
  push:
  workflow_dispatch:

jobs:
  uni-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm  run test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
